### ISSUE TITLE
make the file sizes displayed human readable

### ISSUE THREAD

**Issue by noornee** [emoist/grabber#1]
hiya!
i would love to make an improvement to this program by making it display sizes of files that are greater than 1024 bytes in other readable formats like KB, MB etc..

**Comment by eroist** [comment]
awesome @noornee

**Comment by noornee** [comment]
alrightt, thankss! @eroist  ^ ^

**Comment by u00t** [comment]
@noornee 
always welcome any contribution!

**Comment by noornee** [comment]
thanks @emoist 
i noticed you didnt handle the error the regular way 
like so 
```go
if err != nil {
  fmt.Println(err)
}
```

why did you choose to do it [this](https://github.com/emoist/grabber/blob/d49d49aa4353517a1afcf1c98b571959f9d4c094/cmd/size.go#L22) way ?
```go

if errors.Is(err, os.ErrNotExist) {
  ...
}
```

**Comment by u00t** [comment]
we can do error handling like you!

**Comment by noornee** [comment]
:D okayy

**Comment by u00t** [comment]
just updated!

**Comment by u00t** [comment]
i will close this issue now
@noornee 
okay?

**Comment by noornee** [comment]
okayy
